server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou?characterEncoding=utf-8
    username: root
    password: root
    #redis配置
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  worker:
    workerId: 1
    dataCenterId: 1
#支付相关配置
  pay:
    wx:
      appID: wx8397f8696b538317  #公众号id
      mchID: 1473426802  #商户号id
      key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb  # 秘钥
      notifyurl: http://a31ef7db.ngrok.io/WeChatPay/WeChatPayNotify  #回调地址
